apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rajesh-test-application
spec:
  destination:
    name: "default"
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: argocd/getting-started
    repoURL: https://github.com/rajeshv-maplelabs/argocd_demo.git
    targetRevision: HEAD
  project: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
